import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import videosRouter from "./videos";
import projectsRouter from "./projects";
import dashboardRouter from "./dashboard";
import adminRouter from "./admin";
import aiEngineRouter from "./ai-engine";
import languagesRouter from "./languages";
import adsRouter from "./ads";
import platformSettingsRouter from "./platform-settings";
import apiPlatformRouter from "./api-platform";
import pronunciationRouter from "./pronunciation";
import offersRouter from "./offers";
import specialAccessRouter from "./special-access";
import soundDesignRouter from "./sound-design";
import marketingAssetsRouter from "./marketing-assets";
import analyticsRouter from "./analytics";
import charactersRouter from "./characters";
import apiV1Router from "./api-v1";
import videoPlansRouter from "./video-plans";
import storeRouter from "./store";

const router: IRouter = Router();

router.use(apiV1Router);
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(videosRouter);
router.use(projectsRouter);
router.use(dashboardRouter);
router.use(adminRouter);
router.use(aiEngineRouter);
router.use(languagesRouter);
router.use(adsRouter);
router.use(platformSettingsRouter);
router.use(apiPlatformRouter);
router.use(pronunciationRouter);
router.use(offersRouter);
router.use(specialAccessRouter);
router.use(soundDesignRouter);
router.use(marketingAssetsRouter);
router.use(analyticsRouter);
router.use(charactersRouter);
router.use(videoPlansRouter);
router.use(storeRouter);

export default router;
